### ISSUE TITLE
Deprecated FlatButton

### ISSUE THREAD

**Issue by arkzuse** [FusionIIIT/Fusion-mobile#79]
Flatbutton class is deprecated.

**Comment by Hemant2000-karens** [comment]
fix it asap, and upgrade dart, flutter, and cradle api(s).

<img width="1107" alt="Screenshot 2023-01-29 at 7 33 40 PM" src="https://user-images.githubusercontent.com/58652350/215331388-373862ef-10b1-4b5f-813d-7852587dc386.png">
